### ISSUE TITLE
Permission to relicense?

### ISSUE THREAD

**Issue by agothro** [skmp/BasicBoy#1]
Hi! I'm writing a game boy emulator for a basic interpreter (long story). I want to use this code for some parts, I was wondering if you could relicense it so that I could use it.

I would greatly prefer MIT or (new) BSD license, if possible, but any free license will do.

**Comment by skmp** [comment]
Is the Apache license not good enough?

**Comment by agothro** [comment]
It's good enough, I had not noticed it and thus closed the issue. It was because the files still say that use is prohibited.
